### ISSUE TITLE
give all team members access to github

### ISSUE THREAD

**Issue by rmalina** [cassininazir/creativedisturbance#100]
ycan tina doesnt have access to git hub

can we give access to github to all team members ? otherwise they cant file bugs

roger

**Comment by porteriffic** [comment]
Sound Team will be given access by Friday.

**Comment by cassininazir** [comment]
Will also discuss how to use GitHub in Friday's meeting.

**Comment by porteriffic** [comment]
Dev team is not on the "Creative Disturbance" Github. I can't assign tasks to dev team.

**Comment by cassininazir** [comment]
This is now fixed. Had to assign them individually to each of the repositories we created.
