### ISSUE TITLE
typos in mohammed yousef podcast

### ISSUE THREAD

**Issue by rmalina** [cassininazir/creativedisturbance#102]
Roger?  

I think that is a bad typo - see my email to Annick.

Thanks, Pam

-------- Original Message --------
Subject:	Re: Fwd: mohammed youself on virtual africa channel of creative disturbance
Date:	Wed, 11 Feb 2015 23:23:23 +0100
From:	Annick Bureaud <abureaud@gmail.com>
Reply-To:	abureaud@gmail.com
To:	Pamela Grant-Ryan <pgr@leonardo.info>

Hi Pam

I am not the one in charge of this, this is Yvan Tina 
together with Roger ;-)

Best
Annick

Le 11/02/15 22:59, Pamela Grant-Ryan a écrit :
> Hi Annick,
>
> There seems to be a typo in this announcement - the name in
> the title is: mohammed youself
> <https://www.linkedin.com/e/v2?e=mwaqm-i61695ph-40&t=gde&midToken=AQF-m9B2pNEYZA&ek=b2_anet_digest&li=1&m=hero&ts=hero-disc-disc-0&itemID=5971152781677977600&itemType=member&anetID=89849>
> - rather than Youssef
> <https://www.linkedin.com/e/v2?e=mwaqm-i61695ph-40&t=gde&midToken=AQF-m9B2pNEYZA&ek=b2_anet_digest&li=6&m=hero&ts=hero-disc-0&itemID=5971152781677977600&itemType=member&anetID=89849>.
>
> On quick glance it almost looks like "mohammed yourself" - I
> did a double-take on that.  Given the current state of
> affairs around all things Islam, I think that's an important
> typo to correct.  It almost sounds like taking the name in
> vain, yikes.
>
> Best,
>
> Pam
>
>
> -------- Original Message --------
> Subject: 	mohammed youself on virtual africa channel of
> creative disturbance
> Date: 	Wed, 11 Feb 2015 20:30:22 +0000 (UTC)
> From: 	Leonardo/OLATS <groups-noreply@linkedin.com>
> To: 	Pamela Grant-Ryan <pgr@leonardo.info>
>
>
>
> LinkedIn
> <https://www.linkedin.com/e/v2?e=mwaqm-i61695ph-40&t=nmp&midToken=AQF-m9B2pNEYZA&ek=b2_anet_digest>
> 	
>
> 	Groups
>
> 	
>
> 	
>
> 	Leonardo/OLATS
> <https://www.linkedin.com/e/v2?e=mwaqm-i61695ph-40&t=gmp&midToken=AQF-m9B2pNEYZA&ek=b2_anet_digest&li=0&m=hero&ts=view_group&gid=89849>
> 	
>
> 	
> Trending discussions in:
> Leonardo/OLATS
> <https://www.linkedin.com/e/v2?e=mwaqm-i61695ph-40&t=gmp&midToken=AQF-m9B2pNEYZA&ek=b2_anet_digest&li=0&m=hero&ts=view_group&gid=89849>
>
>
> 	
>
>

**Comment by cassininazir** [comment]
I'm not seeing where this was misspelled. Did someone take care of this already @porteriffic?

**Comment by porteriffic** [comment]
It's on LinkedIn, I believe. So whoever shared it there? I don't think WP even posts to LinkedIn. Just Twitter and Facebook?

**Comment by cassininazir** [comment]
I re-read the original thread closer. It could be read as "Mohamed Yourself" which we definitely don't want. Renamed it from 

Recontre avec Mohamed Youssef-RamiMed

to 

Recontre avec M. Youssef-RamiMed

**Comment by rmalina** [comment]
I fixed it on linked in
My error

roger malina

**Comment by cassininazir** [comment]
No worries. Actually, glad we changed the title because of what could be read into it.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas
