### ISSUE TITLE
Meet the Team Page - Updates

### ISSUE THREAD

**Issue by heiwanalady** [cassininazir/creativedisturbance#104]
Need to add Josephine, Corey, and Ashton.
I have asked them to send me or Vivek their short bios. (Stephanie can help with this)

Also need to set up a "Former Student / Lab Interns" (put Stephen Witt in there - as he no longer works for us).

**Comment by cassininazir** [comment]
Received Josey's. Waiting for the Hal, Ashton and Corey.

**Comment by vivraman** [comment]
Also would like to include CD Alumni (don't need their photos):

Cathryn Ploehn
http://creativedisturbance.org/meet-the-team/

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#7
