### ISSUE TITLE
podcast invitations to donors above

### ISSUE THREAD

**Issue by rmalina** [cassininazir/creativedisturbance#105]
stephanie
we promisted to post podcasts donors who gave more than 50$
we need to send them a message inviting them to stubmit-
can you prepare something and i will post it on kickstarter ?

you can use those draft guidleines i used for people to submit podcasts
and improve it

- we need to send a message soon to all the kickstarter donors with an update also

roger

**Comment by heiwanalady** [comment]
Done!
