### ISSUE TITLE
Missing Voices - Richard Wirth

### ISSUE THREAD

**Issue by heiwanalady** [cassininazir/creativedisturbance#108]
Richard Wirth is currently not on the Voices list. He has participated in at least one podcast. 
Who is in charge of keeping the website updated as far as new voices? @vivraman ? 

(Roger discovered he was missing this morning)

**Comment by vivraman** [comment]
Done.

http://creativedisturbance.org/people/richard-wirth/

**Comment by rmalina** [comment]
much thanks
roger

On Thu, Feb 26, 2015 at 1:01 AM, vivraman <notifications@github.com> wrote:

> Closed #108
> <https://github.com/cassininazir/creativedisturbance/issues/108>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cassininazir/creativedisturbance/issues/108#event-242298403>
> .
>



-- 
Roger F Malina
is in dallas
1-510-853-2007
