### ISSUE TITLE
glitch in podcast appearint on featured but not on channel

### ISSUE THREAD

**Issue by rmalina** [cassininazir/creativedisturbance#115]
the new sound and data podcast is up
http://creativedisturbance.org/podcast/margaret-schedel-and-the-sounds-of-science/

but it doesnt show up on the channel

http://creativedisturbance.org/channel/sound-data/

roger

**Comment by porteriffic** [comment]
I just fixed it. Give it a few minutes before it actually pops up.

**Comment by sayloo** [comment]
The "Direct Download URL" should be given and not the permalink. Its now working.
