### ISSUE TITLE
double podcast posting

### ISSUE THREAD

**Issue by rmalina** [cassininazir/creativedisturbance#119]
its very embarassing but we have the same podcast up twice for the paszt 48 houirs

http://creativedisturbance.org/podcast/roots-of-curiosity-conference-with-patricia-correia-2/

http://creativedisturbance.org/podcast/roots-of-curiosity-conference-with-patricia-correia/

with different titles and both are wrong-only one of the voices is in the title wy bot all gthree

can someone take down the duplicate podcast ? or is it different and the title of the second is
wrong

roger

**Comment by cassininazir** [comment]
I've taken down the Portuguese version from the home page and updated the titles of the podcasts. 

The Portuguese version's title should be in Portuguese, not in English. Will ask the team to work on this.

**Comment by porteriffic** [comment]
Also added "featured voices" in the name of title (if their name wasn't in the title already).
I'm currently working with a friend of mine to translate the Portuguese title for me. Should be updated by late tonight or early tomorrow.
