### ISSUE TITLE
languages

### ISSUE THREAD

**Issue by rmalina** [cassininazir/creativedisturbance#121]
we have a real problem that we dont indicate the language of each podcast when we list
it on featured page or under each channel list- its really stupid that you have to click on the podcast itself to figure out what language its in-can we indicate clearly in the TITLE of each podcast what language it is in
roger

**Comment by porteriffic** [comment]
Roger,

The GitHub you are posting on is Cassini's personal GitHub. Cassini has
created a GitHub account for Creative Disturbance here
<https://github.com/creativedisturbance>.

I will make note of this at our meeting so that the issues you've posted
can be put on the Creative Disturbance GitHub. Sorry about the confusion.

Best,
Josephine

**Comment by rmalina** [comment]
total confusion !
maybe i now have two separate github accounts !!

apologies
roger

On Sun, Mar 29, 2015 at 5:35 PM, porteriffic <notifications@github.com>
wrote:

> Roger,
>
> The GitHub you are posting on is Cassini's personal GitHub. Cassini has
> created a GitHub account for Creative Disturbance here
> <https://github.com/creativedisturbance>.
>
> I will make note of this at our meeting so that the issues you've posted
> can be put on the Creative Disturbance GitHub. Sorry about the confusion.
>
> Best,
> Josephine
>
> On Sun, Mar 29, 2015 at 9:58 AM, rmalina <notifications@github.com> wrote:
>
> > we have a real problem that we dont indicate the language of each podcast
> > when we list
> > it on featured page or under each channel list- its really stupid that
> you
> > have to click on the podcast itself to figure out what language its
> in-can
> > we indicate clearly in the TITLE of each podcast what language it is in
> > roger
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cassininazir/creativedisturbance/issues/121>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cassininazir/creativedisturbance/issues/121#issuecomment-87491245>
> .
>



-- 
Roger F Malina
is in texas
1-510-853-2007

**Comment by cassininazir** [comment]
Sorry for the confusion! The earlier project was filed under my GitHub account. This new one has been setup as a project in GitHub (independent of user) and makes it easier to collab and admin.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas
