### ISSUE TITLE
Update Meet the Team Page

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#41]
We will be taking team photos on Friday, Jan. 30. Would like you to update the Meet the Team page with the new photos and bios. 

Also would like to include CD Alumni (don't need their photos):

- Cathryn Ploehn

http://creativedisturbance.org/meet-the-team/

**Comment by cassininazir** [comment]
Won't be able implement until we get photos from Jan. 30 meeting.

**Comment by vivraman** [comment]
Photos are updated for existing team members, but I'm not sure where the new bios are.

Anyone wanna point me in the right direction?

**Comment by cassininazir** [comment]
Need Hal, Josey, Ashton.

**Comment by porteriffic** [comment]
Do we go in WP to type our bios?

**Comment by cassininazir** [comment]
This is a duplicate of #104. Closing this one.
