### ISSUE TITLE
Include contact info for producers on the channel page

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#42]
Discussed putting this information on the Producer's profile page. Rather than putting email address in plain text on the page, create a form that would allow individuals to send that person an email without disclosing the email address.

**Comment by cassininazir** [comment]
Discussed ƒixing in:

- line-height
- text-align (left)
- padding

**Comment by cassininazir** [comment]
Status update by Feb. 13

**Comment by sayloo** [comment]
Try to get the channel_authors for a channel and get their email addresses.

Also, play with contact Form 7 plugin.

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#17
