### ISSUE TITLE
Data Audit Part 1

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#45]
Review the Google Analytics data to identify browsers that have usage greater than 1%. This list should include
- browsers
- operating systems 
- and devices

**Comment by cassininazir** [comment]
This will help the dev team in testing and development environs.

**Comment by cassininazir** [comment]
Agreed upon Friday, Jan. 30 as a delivery date. Create this in Google Drive under the 2.1 Folder. Name it what you'd like. 

Recommend reviewing the two docs I sent you prior to cataloguing.

**Comment by vivraman** [comment]
Done as of Friday afternoon, forgot to close

**Comment by cassininazir** [comment]
Thanks, Vivek. When you close can you also link to or give the name of where we can find the doc in Google Drive?

**Comment by vivraman** [comment]
Got it.

Link is here: https://docs.google.com/document/d/13mGZkg9h4-FSSFzgaCf04NeICXv6pAk959MW-jxf06I/edit?usp=drive_web

**Comment by vivraman** [comment]
Focus more on what data we can access instead of what the data actually is

**Comment by vivraman** [comment]
Done, forgot to add and close.

https://docs.google.com/spreadsheets/d/1UFV0t3Q-Vm1GSC8Fixwkvbq3u-Mf_qrWNRPO-5wS9MA/edit?usp=drive_web
