### ISSUE TITLE
Propose fixes for non-English speaking users

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#50]
When a user clicks on the a flag can you prioritize the podcasts listed on the home page to include that language first? If we do this on the home page, can we do this also on the Disturbances page?

**Comment by sayloo** [comment]
Try on the production server.

List out the feature on the Disturbances page

**Comment by sayloo** [comment]
LATCH ( Location/Language* Alphabetical Time ( New channel but not new podcast) Category Hierarchy ) 

Alpha | Language -(preferred language)  | Newest

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#16
