### ISSUE TITLE
Research auto post from WordPress to Libsyn (or vice versa) 

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#52]
Is it possible to simplify the process of posting from WordPress to Libsyn. The process of updating both WordPress and Libsyn is complicated and introduces the possibility for errors. Would like to see a solution that simplifies this process (not having to login to two places and post the same content) and reduces possibility of errors. 

Cursory Google Search pulled the following up. Please investigate.

http://support.libsyn.com/faqs/wordpress-onpublish/

**Comment by anvit** [comment]
Experiment with python wordpress library and write up a script for reading rss data from libsyn and posting a draft on the wordpress site.

**Comment by cassininazir** [comment]
A few things that came out of the sound team meeting when adding a new podcast:  

- There are two areas for descriptions. Which should the sound team use? (currently using both)
- Can "Topics" be changed to "Keywords" (to match what is in Wufoo form)
- Can "Episode Name" be changed to "Podcast Title"
- "Primary channel" and "Channel" a bit confusing. Can we rename "Channel" to "Secondary Channel" and make it not required.

**Comment by cassininazir** [comment]
Make sure we discuss with AUdio team.
URL creation in LibSyn needs to be reflected in WordPress. 
When stripping HTML remove styling, etc except for 
 - <a>
 - <em>, <i>
 - <strong>,<b>
 - <p>, <br>
 - <img> ???

**Comment by cassininazir** [comment]
The audio team has noticed that when uploading a podcast whose filename has accents, LibSyn will remove the accent from the name. There was a file that the sound team uploaded that worked on LibSyn but when they copied over the name into WordPress, didn't work when the team published. Not sure how this happened, but needs investigation.

**Comment by cassininazir** [comment]
Comment when you have a alpha to test. Will get the sound team to review and check before we launch.

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#23
