### ISSUE TITLE
Style Guide for Written Content

### ISSUE THREAD

**Issue by vivraman** [cassininazir/creativedisturbance#54]
CD needs a style guide that producers, blog posters, etc. will abide by when any kind of written content is posted to the website.

**Comment by cassininazir** [comment]
Let's work on this together in early Feb.

**Comment by vivraman** [comment]
https://docs.google.com/document/d/1nrUkMff88j0MpISRupbwQueasobyUtaXlMG6J587N4Q/edit

Add additional points, clean up overall, tell @cassininazir when finished for final edits.

Send draft as it stands to Sound team + Kyle.

**Comment by vivraman** [comment]
Done, Cassini will inform Sound team of the document (mini-lecture).
