### ISSUE TITLE
Fix Text Issues on Individual Disturbance Pages

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#55]
Discussed fixing:

- line-height
- text-align (left)
- padding

See attached image for reference. 

![screen shot 2015-01-26 at 12 17 02 pm](https://cloud.githubusercontent.com/assets/1661430/5905312/0144ba24-a555-11e4-8b84-c88a7da1c890.png)

**Comment by cassininazir** [comment]
This screenshot better describes the issue.

![screen shot 2015-01-26 at 12 18 13 pm](https://cloud.githubusercontent.com/assets/1661430/5905324/127a5146-a555-11e4-9d5d-c02028078584.png)

**Comment by sayloo** [comment]
Fixed everything on chrome. Now things look neater. Applied line height and padding.
