### ISSUE TITLE
Create Frank Malina Channel

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#60]
Sruthi, please create the Frank Malina channel in WordPress. Stephanie has uploaded album art to the Google Drive space (CD > 5.0 Key Public Docs > Album Artwork). The description should be available in Wufoo. 

Please get this up by 30 Jan. and let Ashton know once it is complete. He should then update the album art for the podcasts and Libsyn.

**Comment by sayloo** [comment]
Created the Frank Malina Channel. The channel will auto publish on Jan 30 at 00:30. Will inform Ashton.
