### ISSUE TITLE
Data Audit Part 2

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#61]
Complete by Feb. 6. Will need a data audit for (in order of importance): 

- LibSyn
- iTunes 
- Kickstarter
- WordPress
- Facebook Insights
- Twitter

Use the Google Doc Spreasheet that you started for Google Analytics info.

**Comment by vivraman** [comment]
Done, forgot to add and close.

https://docs.google.com/spreadsheets/d/1UFV0t3Q-Vm1GSC8Fixwkvbq3u-Mf_qrWNRPO-5wS9MA/edit?usp=drive_web

Need to discuss Wordpress and iTunes data sources, could not find them when I looked. From my research I don't think iTunes has an analytics section, though I'm not sure about this.

**Comment by cassininazir** [comment]
Nice job. I�m looking forward to digging into this.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by vivraman** [comment]
Look at Wordpress user data, add to spreadsheet

**Comment by vivraman** [comment]
Done, new tab in spreadsheet.

**Comment by vivraman** [comment]
Woops.

**Comment by cassininazir** [comment]
@cassininazir is reviewing the data currently. Will produce KPIs.
