### ISSUE TITLE
Get Radio Play from Scot Gresham-Lancaster

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#65]
Scot mentioned that students worked on a radio play (I may have the name wrong). Email Scot requesting this by Friday, Jan. 30.

**Comment by vivraman** [comment]
Update: he has "some radio play related material but its not ready yet"; he said he'll let us know when it's ready.

I'll probably bug him again in a week or so.

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#9
