### ISSUE TITLE
Change flags to language names in CD Header

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#66]
Anvit, 

Had some good feedback from Annick. Her recommendation is to change the French flag to instead have the words "Français". Having the French flag might irritate Canadians, Africans and other French speakers. 

So this image on CD

![screen shot 2015-01-30 at 10 16 27 am](https://cloud.githubusercontent.com/assets/1661430/5978927/fd24b072-a868-11e4-8612-a0ae746e12b8.png)

Might look something like this (taken from the Facebook login page)

![screen shot 2015-01-30 at 10 16 43 am](https://cloud.githubusercontent.com/assets/1661430/5978937/0701c53a-a869-11e4-9e66-fe21301e9720.png)

For now, let's list

- English
- Français
- Español
- ... 

In that order. The ellipsis should take the user to a page to request a language. We should allow users to tell us what language they'd like to listen/read in.

**Comment by anvit** [comment]
Replacing the current flag widget with another widget provided on the official transposh website.

**Comment by anvit** [comment]
Changed the language widget to one without flags. Since options for widgets are very limited with transposh (http://transposh.org/tutorial/widget-showcase/) and writing our own widget or modifying the widget would be overwritten by plugin updates, closing the issue for now. Will start looking into other translation engines which provide more customization.

**Comment by cassininazir** [comment]
Really need to remove the flags. Looks like a 

img.flag { display: none } 

Will do the trick. Could you implement this?

**Comment by anvit** [comment]
Done. Moving additional code to Custom CSS section in 'Theme options' so that these changes are easy to locate.

**Comment by rmalina** [comment]
anvit- i dont understand- i picked english as the language but the top podcasts on the page were in french !
i thought the idea is when we pick the language it features podcasts in that language ?
anyway i sent an email-lets discuss in the design meeting with a session on multilingual
roger

**Comment by cassininazir** [comment]
Anvit, could you open a new task for what Roger has described in his comments.
