### ISSUE TITLE
Create new channel for Cellphonia

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#70]
When Stephanie completes the album artwork, please create the Channel for this. Work with sound team on when this will go out.

**Comment by vivraman** [comment]
Channel is ready to go up except artwork, waiting for Stephanie to get back to me so I can add that.

**Comment by cassininazir** [comment]
From convo with Scot:

- Will have podcasts with the experimenters discussing content (this will actually go into the Sound and Data channel)
- Will also need to have the Experimental space go up at the same time that the podcast goes up

**Comment by cassininazir** [comment]
@heiwanalady's artwork is being finalized. Don't publish until we have first podcast.

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#8
