### ISSUE TITLE
Update WordPress to 4.1

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#81]
Investigate what the fallout is of updating.

**Comment by anvit** [comment]
Issues with updating 'WPBakery Visual Composer' and 'WPMU DEV Dashboard'. Manual update required because of API key error.

**Comment by cassininazir** [comment]
Theme plugin giving trouble. 

- Will need Envato username and API key. 
- Will need to duplicate live info on production server.

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#21
