### ISSUE TITLE
Create Experimental Space

### ISSUE THREAD

**Issue by vivraman** [cassininazir/creativedisturbance#83]
Work with @anvit to create a section in Wordpress for the new Experimental section.

Coordinate with @cassininazir when scheduling a time to work on this.

**Comment by cassininazir** [comment]
Vivek, let's make this a priority. This will need to be up by end of Feb.

**Comment by vivraman** [comment]
Yes I agree, in the next dev team meeting let's flesh out a time with Anvit
to work out the logistics of creating the space.

I'm travelling at the moment but I will try to have a draft of the
experimental space guidelines to you asap.

**Comment by cassininazir** [comment]
URL should be a subdomain of creativedisturbance.org. Users should be able to login with their current WordPress account and publish to this subdomain. 

Should also have "playground" access to post code or a piece.

**Comment by cassininazir** [comment]
Created! at x.creativedisturbance.org
