### ISSUE TITLE
Add DOI functionality to website

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#87]
We need to include a Digital Object Identifier (akin to a permalink) for each podcast. May require a bit of research to implement this functionality. 

- www.crossref.org
- http://www.doi.org

**Comment by cassininazir** [comment]
May be a WordPress plugin that has this. KCite plugin?

**Comment by anvit** [comment]
Need to purchase DOI from crossref: http://www.crossref.org/02publishers/20pub_fees.html

**Comment by cassininazir** [comment]
Contacted Matt Makowka about piggy-backing off of the Library's access, if possible. If not, will have Brett purchase

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#20
