### ISSUE TITLE
Audiolats Channel

### ISSUE THREAD

**Issue by sayloo** [cassininazir/creativedisturbance#89]

**Comment by cassininazir** [comment]
Only missing album art at this point. Check to see whether Yvan's email attachment fits the requirements for album art.

**Comment by cassininazir** [comment]
Podcasts from P&P that have been uploaded recently are there temporarily. Once Audiolats channel goes up place move the P&P into Audiolats.

**Comment by cassininazir** [comment]
Make sure Jean-Luc Soret is among  the producers

**Comment by heiwanalady** [comment]
Just sent the album art to the team to be reviewed

**Comment by sayloo** [comment]
Done! Everything is up.

**Comment by cassininazir** [comment]
Thanks for getting this up so quickly, Sruthi
