### ISSUE TITLE
Channel + Primary Channel Duplication

### ISSUE THREAD

**Issue by cassininazir** [cassininazir/creativedisturbance#93]
We need to make the process of a podcast appear in two Channels easier. The "channel + primary channel" tags should not require an admin to create two separate posts. Can we:

- Change "Channel" to "Primary Channel"
- Change "Primary Channel" to "Secondary Channel"
- Make "Secondary Channel" optional
- Make anything with a "Secondary Channel" appear on the appropriate channel

**Comment by sayloo** [comment]
1. Changed "Channel" to "Primary Channel"
2. Changed "Primary Channel" to "Secondary Channel"
3. Made "Secondary Channel" optional
4. This cannot be done. We cannot make a post appear in 2 different channels with just one post in wordpress.

**Comment by cassininazir** [comment]
How is this different from tagging? Using WordPress tags I can make a post appear in multiple contexts. This has to be possible.

**Comment by cassininazir** [comment]
Implement on production server first.

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/public-website#14
