### ISSUE TITLE
given producers access so they can deposit podcasts into drop box

### ISSUE THREAD

**Issue by rmalina** [cassininazir/creativedisturbance#99]
=
have all producers been given access to drop box so they can deposit
podcast ?

scot gresham lancaster did not

can you send an email to all producers explaining them how to deposit podcasts into
drop box and give them access

roger

Sorry about that! Josephine, can you give Scot access to the dropbox? I do not think I have that power.

- Hal

----- Original Message -----
From: "Scot Gresham-Lancaster" <scotgl@gmail.com>
To: "Hal Clark" <hclark55@gmail.com>
Cc: "Roger Malina" <rxm116130@utdallas.edu>, "Theodore Clark" <thc140130@utdallas.edu>
Sent: Tuesday, February 10, 2015 4:16:19 PM
Subject: Re: sonification podcast

This dropbox is not enabled for upload for me. Please advise

**Comment by cassininazir** [comment]
Josephine, I'm assigning this to you for the moment. You may choose to delegate to other sound team members when they have access.

**Comment by porteriffic** [comment]
I've already created an issue for this. It has been resolved. I just need to email the producer's the "Share" link to the Dropbox.

**Comment by cassininazir** [comment]
Go ahead and hit "Close Issue" at the bottom of this issue. I won't deprive you of the joy.
